### ISSUE TITLE
adapter failure after initial installation

### ISSUE THREAD

**Issue by KaiHannemann** [RealVNF/bjointsp-adapter#2]
```
(venv) (base) G:\bjointsp-adapter>bjointsp-adapter -n "res/networks/triangle.graphml" -sf "res/service_functions/abc.yaml" -c "res/config/sim_config.yaml" -i 50
sfc_1's weight: 6.0

Best overlays:
Overlay of sfc_1
        4 instances: (vnf_source,pop0):[f1] (a,pop0) (b,pop0) (c,pop0)
        3 edges: (vnf_source,pop0):[f1]->(a,pop0):[f1] (a,pop0)->(b,pop0):[f1] (b,pop0)->(c,pop0):[f1]
Writing solution to results/bjointsp\triangle-sfc_1-first_source-2019-09-24_13-10-15_2034.yaml
Traceback (most recent call last):
  File "g:\bjointsp-adapter\venv\lib\site-packages\coordsim\simulation\flowsimulator.py", line 205, in process_flow
    demanded_total_capacity += self.params.sf_list[sf_i]['resource_function'](sf_data['load'])
KeyError: 'vnf_source'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\bjointsp-adapter\venv\lib\site-packages\coordsim\simulation\flowsimulator.py", line 121, in pass_flow
    yield self.env.process(self.process_flow(flow, sfc))
KeyError: 'vnf_source'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\bjointsp-adapter\venv\lib\site-packages\coordsim\simulation\flowsimulator.py", line 96, in init_flow
    yield self.env.process(self.pass_flow(flow, sfc))
KeyError: 'vnf_source'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\bjointsp-adapter\venv\Scripts\bjointsp-adapter-script.py", line 11, in <module>
    load_entry_point('bjointsp-adapter==0.0.2', 'console_scripts', 'bjointsp-adapter')()
  File "g:\bjointsp-adapter\venv\lib\site-packages\adapter\adapter.py", line 104, in main
    apply_state = simulator.apply(action)
  File "g:\bjointsp-adapter\venv\lib\site-packages\siminterface\simulator.py", line 113, in apply
    self.env.run(until=runtime_steps)
  File "g:\bjointsp-adapter\venv\lib\site-packages\simpy\core.py", line 138, in run
    self.step()
  File "g:\bjointsp-adapter\venv\lib\site-packages\simpy\core.py", line 230, in step
    raise exc
KeyError: 'vnf_source'
```

**Comment by stefanbschneider** [comment]
@KaiHannemann Issue should be fixed now, please test again.
